//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestão_de_Frota_de_Automóveis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kilometros
    {
        public int Id_Viatura { get; set; }
        public string Matricula { get; set; }
        public string DataRegisto { get; set; }
        public string Kilometros1 { get; set; }
    
        public virtual Viatura Viatura { get; set; }
    }
}
