//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestão_de_Frota_de_Automóveis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestão_de_Frota_de_AutomoveisEntities : DbContext
    {
        public Gestão_de_Frota_de_AutomoveisEntities()
            : base("name=Gestão_de_Frota_de_AutomoveisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Despesa> Despesa { get; set; }
        public virtual DbSet<Fornecedores> Fornecedores { get; set; }
        public virtual DbSet<Kilometros> Kilometros { get; set; }
        public virtual DbSet<Manutençao> Manutençao { get; set; }
        public virtual DbSet<Utilizaçao_Permanente> Utilizaçao_Permanente { get; set; }
        public virtual DbSet<Utilizaçao_Temporaria> Utilizaçao_Temporaria { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
        public virtual DbSet<Viatura> Viatura { get; set; }
    }
}
